# Generated by Django 5.2.8 on 2025-11-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('ESTUDIANTE', 'Estudiante'), ('INVITADO', 'Invitado')], max_length=20)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('RESERVA', 'Reserva creada')], max_length=20)),
                ('username', models.CharField(blank=True, help_text='Nombre de usuario (en el caso del administrador)', max_length=150, null=True)),
                ('rut', models.CharField(blank=True, help_text='RUT del estudiante si aplica', max_length=12, null=True)),
                ('carrera', models.CharField(blank=True, help_text='Carrera del estudiante si aplica', max_length=100, null=True)),
                ('detalle', models.CharField(blank=True, help_text='Detalle adicional (ej: sala reservada, etc.)', max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
